ip: "0.0.0.0"
verbosity: true

smtp:
  port: 587
  user: "smtp-user"
  password: "smtp-password"
  mailDirectory: "/var/mail"
  logMailContents: true

web:
  port: 8080
  user: "web-user"
  password: "web-password"
  disable: false
